# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto-files/TopicDetectionService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto-files/TopicDetectionService.proto',
  package='dreipc.asset.topicmodeling',
  syntax='proto3',
  serialized_options=b'\n\037dreipc.q8r.proto.asset.documentB\024TopicDetectionProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'proto-files/TopicDetectionService.proto\x12\x1a\x64reipc.asset.topicmodeling\"S\n\x19TopicDetectionActionProto\x12\x12\n\ndocumentId\x18\x01 \x01(\t\x12\x11\n\tprojectId\x18\x02 \x01(\t\x12\x0f\n\x07\x66ileUrl\x18\x03 \x01(\t\"\x98\x01\n\x18TopicDeletionActionProto\x12\x12\n\ndocumentId\x18\x01 \x01(\t\x12\x11\n\tprojectId\x18\x02 \x01(\t\x12\x12\n\nprovidedBy\x18\x03 \x01(\t\x12\x41\n\x06status\x18\x04 \x01(\x0e\x32\x31.dreipc.asset.topicmodeling.EnrichmentStatusProto\"\x92\x02\n\x13TopicDetectionProto\x12\x12\n\ndocumentId\x18\x01 \x01(\t\x12\x11\n\tprojectId\x18\x02 \x01(\t\x12<\n\x06topics\x18\x03 \x03(\x0b\x32,.dreipc.asset.topicmodeling.TopicObjectProto\x12\x12\n\nprovidedBy\x18\x04 \x01(\t\x12\x41\n\x06status\x18\x05 \x01(\x0e\x32\x31.dreipc.asset.topicmodeling.EnrichmentStatusProto\x12?\n\npageTopics\x18\x06 \x03(\x0b\x32+.dreipc.asset.topicmodeling.PageTopicsProto\"1\n\x0fPageTopicsProto\x12\x0e\n\x06topics\x18\x01 \x03(\t\x12\x0e\n\x06pageId\x18\x02 \x01(\t\"!\n\x10TopicObjectProto\x12\r\n\x05topic\x18\x01 \x01(\t*X\n\x15\x45nrichmentStatusProto\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x12\x0c\n\x08VERIFIED\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x42\x37\n\x1f\x64reipc.q8r.proto.asset.documentB\x14TopicDetectionProtosb\x06proto3'
)

_ENRICHMENTSTATUSPROTO = _descriptor.EnumDescriptor(
  name='EnrichmentStatusProto',
  full_name='dreipc.asset.topicmodeling.EnrichmentStatusProto',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_STARTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERIFIED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=674,
  serialized_end=762,
)
_sym_db.RegisterEnumDescriptor(_ENRICHMENTSTATUSPROTO)

EnrichmentStatusProto = enum_type_wrapper.EnumTypeWrapper(_ENRICHMENTSTATUSPROTO)
NOT_STARTED = 0
PENDING = 1
DONE = 2
VERIFIED = 3
ERROR = 4



_TOPICDETECTIONACTIONPROTO = _descriptor.Descriptor(
  name='TopicDetectionActionProto',
  full_name='dreipc.asset.topicmodeling.TopicDetectionActionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='documentId', full_name='dreipc.asset.topicmodeling.TopicDetectionActionProto.documentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='projectId', full_name='dreipc.asset.topicmodeling.TopicDetectionActionProto.projectId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileUrl', full_name='dreipc.asset.topicmodeling.TopicDetectionActionProto.fileUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=154,
)


_TOPICDELETIONACTIONPROTO = _descriptor.Descriptor(
  name='TopicDeletionActionProto',
  full_name='dreipc.asset.topicmodeling.TopicDeletionActionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='documentId', full_name='dreipc.asset.topicmodeling.TopicDeletionActionProto.documentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='projectId', full_name='dreipc.asset.topicmodeling.TopicDeletionActionProto.projectId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='providedBy', full_name='dreipc.asset.topicmodeling.TopicDeletionActionProto.providedBy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='dreipc.asset.topicmodeling.TopicDeletionActionProto.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=309,
)


_TOPICDETECTIONPROTO = _descriptor.Descriptor(
  name='TopicDetectionProto',
  full_name='dreipc.asset.topicmodeling.TopicDetectionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='documentId', full_name='dreipc.asset.topicmodeling.TopicDetectionProto.documentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='projectId', full_name='dreipc.asset.topicmodeling.TopicDetectionProto.projectId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topics', full_name='dreipc.asset.topicmodeling.TopicDetectionProto.topics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='providedBy', full_name='dreipc.asset.topicmodeling.TopicDetectionProto.providedBy', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='dreipc.asset.topicmodeling.TopicDetectionProto.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageTopics', full_name='dreipc.asset.topicmodeling.TopicDetectionProto.pageTopics', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=586,
)


_PAGETOPICSPROTO = _descriptor.Descriptor(
  name='PageTopicsProto',
  full_name='dreipc.asset.topicmodeling.PageTopicsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='dreipc.asset.topicmodeling.PageTopicsProto.topics', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageId', full_name='dreipc.asset.topicmodeling.PageTopicsProto.pageId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=637,
)


_TOPICOBJECTPROTO = _descriptor.Descriptor(
  name='TopicObjectProto',
  full_name='dreipc.asset.topicmodeling.TopicObjectProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='dreipc.asset.topicmodeling.TopicObjectProto.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=672,
)

_TOPICDELETIONACTIONPROTO.fields_by_name['status'].enum_type = _ENRICHMENTSTATUSPROTO
_TOPICDETECTIONPROTO.fields_by_name['topics'].message_type = _TOPICOBJECTPROTO
_TOPICDETECTIONPROTO.fields_by_name['status'].enum_type = _ENRICHMENTSTATUSPROTO
_TOPICDETECTIONPROTO.fields_by_name['pageTopics'].message_type = _PAGETOPICSPROTO
DESCRIPTOR.message_types_by_name['TopicDetectionActionProto'] = _TOPICDETECTIONACTIONPROTO
DESCRIPTOR.message_types_by_name['TopicDeletionActionProto'] = _TOPICDELETIONACTIONPROTO
DESCRIPTOR.message_types_by_name['TopicDetectionProto'] = _TOPICDETECTIONPROTO
DESCRIPTOR.message_types_by_name['PageTopicsProto'] = _PAGETOPICSPROTO
DESCRIPTOR.message_types_by_name['TopicObjectProto'] = _TOPICOBJECTPROTO
DESCRIPTOR.enum_types_by_name['EnrichmentStatusProto'] = _ENRICHMENTSTATUSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicDetectionActionProto = _reflection.GeneratedProtocolMessageType('TopicDetectionActionProto', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDETECTIONACTIONPROTO,
  '__module__' : 'proto_files.TopicDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:dreipc.asset.topicmodeling.TopicDetectionActionProto)
  })
_sym_db.RegisterMessage(TopicDetectionActionProto)

TopicDeletionActionProto = _reflection.GeneratedProtocolMessageType('TopicDeletionActionProto', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDELETIONACTIONPROTO,
  '__module__' : 'proto_files.TopicDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:dreipc.asset.topicmodeling.TopicDeletionActionProto)
  })
_sym_db.RegisterMessage(TopicDeletionActionProto)

TopicDetectionProto = _reflection.GeneratedProtocolMessageType('TopicDetectionProto', (_message.Message,), {
  'DESCRIPTOR' : _TOPICDETECTIONPROTO,
  '__module__' : 'proto_files.TopicDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:dreipc.asset.topicmodeling.TopicDetectionProto)
  })
_sym_db.RegisterMessage(TopicDetectionProto)

PageTopicsProto = _reflection.GeneratedProtocolMessageType('PageTopicsProto', (_message.Message,), {
  'DESCRIPTOR' : _PAGETOPICSPROTO,
  '__module__' : 'proto_files.TopicDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:dreipc.asset.topicmodeling.PageTopicsProto)
  })
_sym_db.RegisterMessage(PageTopicsProto)

TopicObjectProto = _reflection.GeneratedProtocolMessageType('TopicObjectProto', (_message.Message,), {
  'DESCRIPTOR' : _TOPICOBJECTPROTO,
  '__module__' : 'proto_files.TopicDetectionService_pb2'
  # @@protoc_insertion_point(class_scope:dreipc.asset.topicmodeling.TopicObjectProto)
  })
_sym_db.RegisterMessage(TopicObjectProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
