# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto-files/TopicDetectionService.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class EnrichmentStatusProto(betterproto.Enum):
    NOT_STARTED = 0
    PENDING = 1
    DONE = 2
    VERIFIED = 3
    ERROR = 4


@dataclass
class TopicDetectionActionProto(betterproto.Message):
    document_id: str = betterproto.string_field(1)
    project_id: str = betterproto.string_field(2)
    file_url: str = betterproto.string_field(3)


@dataclass
class TopicDeletionActionProto(betterproto.Message):
    document_id: str = betterproto.string_field(1)
    project_id: str = betterproto.string_field(2)
    provided_by: str = betterproto.string_field(3)
    status: "EnrichmentStatusProto" = betterproto.enum_field(4)


@dataclass
class TopicDetectionProto(betterproto.Message):
    document_id: str = betterproto.string_field(1)
    project_id: str = betterproto.string_field(2)
    topics: List["TopicObjectProto"] = betterproto.message_field(3)
    provided_by: str = betterproto.string_field(4)
    status: "EnrichmentStatusProto" = betterproto.enum_field(5)
    page_topics: List["PageTopicsProto"] = betterproto.message_field(6)


@dataclass
class PageTopicsProto(betterproto.Message):
    topics: List[str] = betterproto.string_field(1)
    page_id: str = betterproto.string_field(2)


@dataclass
class TopicObjectProto(betterproto.Message):
    topic: str = betterproto.string_field(1)
